name: Build and Push Docker Image

on:
  workflow_dispatch

env:
  IMAGE_NAME: arpitagrawal445/nodejs-app
  IMAGE_TAG: build-${{ github.run_number }}

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME:$IMAGE_TAG
